# Generated by Django 2.2.5 on 2019-11-15 17:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('product_type', models.TextField()),
                ('cat_size', models.TextField()),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CatTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.TextField()),
                ('cat_name', models.TextField()),
                ('cat_birthday', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='dogtag',
            name='dog_birthday',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='PurchaseCatProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('cat_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.CatProduct')),
            ],
        ),
    ]
